const GOLD = "#D4AF37";
const BLACK = "#0A0A0A";
const GREEN = "#2D9E6B";
const CREAM = "#FAF8F4";
const WHITE = "#FFFFFF";

export interface ThemeColors {
  primary: string;
  gold: string;
  green: string;
  cream: string;
  white: string;
  background: string;
  surface: string;
  text: string;
  textMuted: string;
  textLight: string;
  border: string;
  cardShadow: string;
  inputBg: string;
  headerBg: string;
  tabBarBg: string;
  cardBg: string;
  modalOverlay: string;
  walletBg: string;
  successBg: string;
  errorBg: string;
  sliderInactive: string;
  iconBgGreen: string;
  iconBgBlue: string;
  iconBgPurple: string;
  iconBgOrange: string;
  iconBgRed: string;
  iconBgGrey: string;
  iconFgGreen: string;
  iconFgBlue: string;
  iconFgPurple: string;
  iconFgOrange: string;
  iconFgRed: string;
  iconFgGrey: string;
  danger: string;
  warningAmber: string;
  warningBg: string;
  warningBorder: string;
  warningText: string;
  progressBarBg: string;
  cancelPillBg: string;
  cancelPillBorder: string;
  cancelPillText: string;
  statusActive: string;
  statusDraft: string;
  statusCompleted: string;
  statusPaused: string;
  statusPending: string;
  indigoAccent: string;
  pinkAccent: string;
  heroBannerSubtext: string;
  institutionalCardBg: string;
  institutionalCardBorder: string;
  institutionalCardDivider: string;
  institutionalCardText: string;
  institutionalCardTextMuted: string;
  institutionalCardTextFaint: string;
  planFreeAccent: string;
  linkAccent: string;
  categoryDefaultAccent: string;
}

export const lightTheme: ThemeColors = {
  primary: BLACK,
  gold: GOLD,
  green: GREEN,
  cream: CREAM,
  white: WHITE,
  background: CREAM,
  surface: WHITE,
  text: BLACK,
  textMuted: "#6B6B6B",
  textLight: "#9B9B9B",
  border: "#EBEBEB",
  cardShadow: "rgba(0,0,0,0.08)",
  inputBg: "#F1F1F1",
  headerBg: WHITE,
  tabBarBg: WHITE,
  cardBg: WHITE,
  modalOverlay: "rgba(0,0,0,0.4)",
  walletBg: GREEN,
  successBg: "#E8F5E9",
  errorBg: "#FFEBEE",
  sliderInactive: "#8C8C8C",
  iconBgGreen: "#E8F5E9",
  iconBgBlue: "#E3F2FD",
  iconBgPurple: "#F3E5F5",
  iconBgOrange: "#FFF3E0",
  iconBgRed: "#FFEBEE",
  iconBgGrey: "#F5F5F5",
  iconFgGreen: "#2E7D32",
  iconFgBlue: "#1565C0",
  iconFgPurple: "#7B1FA2",
  iconFgOrange: "#E65100",
  iconFgRed: "#E53935",
  iconFgGrey: "#666666",
  danger: "#E53935",
  warningAmber: "#F59E0B",
  warningBg: "#FFF8E1",
  warningBorder: "#FFE082",
  warningText: "#7B6100",
  progressBarBg: "#E8E8E8",
  cancelPillBg: "#fef3c7",
  cancelPillBorder: "#fde68a",
  cancelPillText: "#92400e",
  statusActive: "#10b981",
  statusDraft: "#94a3b8",
  statusCompleted: "#6366f1",
  statusPaused: "#F59E0B",
  statusPending: "#a855f7",
  indigoAccent: "#6366f1",
  pinkAccent: "#ec4899",
  heroBannerSubtext: "#E3FCEF",
  institutionalCardBg: "#111827",
  institutionalCardBorder: "#1f2937",
  institutionalCardDivider: "#374151",
  institutionalCardText: "#ffffff",
  institutionalCardTextMuted: "#9ca3af",
  institutionalCardTextFaint: "#d1d5db",
  planFreeAccent: "#64748b",
  linkAccent: "#2563eb",
  categoryDefaultAccent: "#059669",
};

export const darkTheme: ThemeColors = {
  primary: "#F5F5F5",
  gold: "#E8C547",
  green: "#3DBB7F",
  cream: "#121212",
  white: "#1E1E1E",
  background: "#121212",
  surface: "#1E1E1E",
  text: "#F5F5F5",
  textMuted: "#A0A0A0",
  textLight: "#6B6B6B",
  border: "#2E2E2E",
  cardShadow: "rgba(0,0,0,0.3)",
  inputBg: "#2A2A2A",
  headerBg: "#121212",
  tabBarBg: "#1A1A1A",
  cardBg: "#1E1E1E",
  modalOverlay: "rgba(0,0,0,0.6)",
  walletBg: "#1B5E3B",
  successBg: "#1B3A26",
  errorBg: "#3A1B1B",
  sliderInactive: "#2E2E2E",
  iconBgGreen: "#1B2E1B",
  iconBgBlue: "#1B2A3D",
  iconBgPurple: "#2D1B3D",
  iconBgOrange: "#3D2A1B",
  iconBgRed: "#3D1515",
  iconBgGrey: "#2A2A2A",
  iconFgGreen: "#4CAF50",
  iconFgBlue: "#42A5F5",
  iconFgPurple: "#CE93D8",
  iconFgOrange: "#FFB74D",
  iconFgRed: "#E53935",
  iconFgGrey: "#666666",
  danger: "#E53935",
  warningAmber: "#F59E0B",
  warningBg: "#2A2000",
  warningBorder: "#5A4500",
  warningText: "#F5C518",
  progressBarBg: "#333333",
  cancelPillBg: "#2D2500",
  cancelPillBorder: "#5C4A00",
  cancelPillText: "#FFC947",
  statusActive: "#10b981",
  statusDraft: "#94a3b8",
  statusCompleted: "#6366f1",
  statusPaused: "#F59E0B",
  statusPending: "#a855f7",
  indigoAccent: "#6366f1",
  pinkAccent: "#ec4899",
  heroBannerSubtext: "#E3FCEF",
  institutionalCardBg: "#111827",
  institutionalCardBorder: "#1f2937",
  institutionalCardDivider: "#374151",
  institutionalCardText: "#ffffff",
  institutionalCardTextMuted: "#9ca3af",
  institutionalCardTextFaint: "#d1d5db",
  planFreeAccent: "#64748b",
  linkAccent: "#60a5fa",
  categoryDefaultAccent: "#059669",
};

const Colors = {
  primary: BLACK,
  gold: GOLD,
  green: GREEN,
  cream: CREAM,
  white: WHITE,
  background: CREAM,
  surface: WHITE,
  text: BLACK,
  textMuted: "#6B6B6B",
  textLight: "#9B9B9B",
  border: "#EBEBEB",
  cardShadow: "rgba(0,0,0,0.08)",
  inputBg: "#F1F1F1",
  headerBg: WHITE,
  tabBarBg: WHITE,
  cardBg: WHITE,
  modalOverlay: "rgba(0,0,0,0.4)",
  walletBg: GREEN,
  successBg: "#E8F5E9",
  errorBg: "#FFEBEE",
  sliderInactive: "#8C8C8C",
  danger: "#E53935",
  planFreeAccent: "#64748b",
  planInstitutionalAccent: "#1a1a2e",
  linkAccent: "#60a5fa",
  categoryDefaultAccent: "#059669",
  light: {
    text: BLACK,
    background: CREAM,
    tint: BLACK,
    tabIconDefault: "#9B9B9B",
    tabIconSelected: BLACK,
  },
};

export default Colors;
